<?php
/**
 * OpenSNS X
 * Copyright 2014-2020 http://www.thisky.com All rights reserved.
 * ----------------------------------------------------------------------
 * Author: 郑钟良(zzl@ourstu.com)
 * Date: 2019/5/24
 * Time: 16:07
 */

namespace app\osapi\model;


use think\Model;

!defined('DATABASE_PREFIX')&&define('DATABASE_PREFIX', config('database.prefix'));

class BaseModel extends Model
{

    protected static $error_message='';
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        self::getConnection()->setConfig('datetime_format',false);
    }

    /**
     * 添加一条数据并返回id
     * @param $data
     * @return int|string
     * @author 郑钟良(zzl@ourstu.com)
     * @date slf
     */
    public static function add($data)
    {
        $object=self::create($data);
        return $object->getLastInsID();
    }

    public static function setErrorInfo($error='操作失败')
    {
        self::$error_message=$error;
        return true;
    }

    /**
     * 模型执行向外报错信息
     * @return string
     * @author 郑钟良(zzl@ourstu.com)
     * @date slf
     */
    public static function getErrorInfo()
    {
        return self::$error_message;
    }

    /**
     * 开启事务
     */
    public static function beginTrans()
    {
        self::startTrans();
    }

    /**
     * 提交事务
     */
    public static function commitTrans()
    {
        self::commit();
    }

    /**
     * 回滚事务
     */
    public static function rollbackTrans()
    {
        self::rollback();
    }

    /**
     * 根据结果提交滚回事务
     * @param $res
     */
    public static function checkTrans($res)
    {
        if($res){
            self::commitTrans();
        }else{
            self::rollbackTrans();
        }
    }
}